export const ui = {
  hoursHeading: "Hours",
  contactHeading: "Desk",
  addressHeading: "Find us",
  quickLinksHeading: "The room",
  getDirections: "Get directions",
  callAria: "Call Gulmohar Kitchen",
  whatsappAria: "WhatsApp Gulmohar Kitchen",
  orderOnline: "Order in",
  veg: "Vegetarian",
  nonveg: "Non-vegetarian",
  jain: "Jain",
  bestseller: "Bestseller",
  spice: "Spice",
  rupeePrefix: "₹",
  mapTitle: "Map of Gulmohar Kitchen on College Road, Nashik",
  reviewsHeading: "Guests",
  starsAria: "star rating",
  formErrors: {
    name: "Tell us who to put the table under.",
    phone: "Give a 10-digit Indian mobile number.",
    date: "Pick a date from today onward.",
    time: "Choose a seating time.",
    party: "How many chairs should we keep?",
    generic: "Please check the highlighted fields.",
  },
  a11y: {
    spiceLevel: "Spice level",
  },
  close: "Close",
} as const;
